name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t helloworld:ubuntu .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into VM and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" &gt; private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key user@your_vm_ip &lt;&lt; 'EOF'
            cd /my_repo
            sudo docker stop helloworld:ubuntu || true
            sudo docker rm helloworld:ubuntu || true
            git pull origin master
            sudo docker build -t helloworld:ubuntu .
            sudo docker run helloworld:ubunt
          EOF
