name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t helloworld:ubuntu .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into VM and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" &gt; private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key superuser@192.168.210.148 &lt;&lt; 'EOF'
            cd ~/my_repo
            docker stop helloworld || true
            docker rm helloworld || true
            git pull
            sudo docker build -t helloworld:ubuntu .
            sudo docker run --name=helloworld helloworld:ubuntu
          EOF
